using UnityEngine;

namespace AetherFrame
{
    // Handles player firing cadence and projectile spawning. Projectile prefabs are scene
    // templates generated by the editor builder, then activated after instantiation.
    public sealed class WeaponController : MonoBehaviour
    {
        [Header("References")]
        public Transform laserMuzzle;
        public Transform missileMuzzle;
        public Projectile laserPrefab;
        public HomingMissile missilePrefab;
        public LockOnSystem lockOnSystem;
        public Team team = Team.Player;

        [Header("Fire Rates")]
        public float laserCooldown = 0.14f;
        public float missileCooldown = 1.1f;

        [Header("Muzzle Flash")]
        public Color muzzleFlashColor = new Color(0.45f, 0.95f, 1f);
        public float flashIntensity = 4f;
        public float flashLifetime = 0.055f;

        private float nextLaserTime;
        private float nextMissileTime;

        private void Update()
        {
            if (Input.GetMouseButton(0) && Time.time >= nextLaserTime)
            {
                nextLaserTime = Time.time + laserCooldown;
                FireLaser();
            }

            if (Input.GetMouseButton(1) && Time.time >= nextMissileTime)
            {
                nextMissileTime = Time.time + missileCooldown;
                FireMissile();
            }
        }

        private void FireLaser()
        {
            if (laserPrefab == null || laserMuzzle == null)
            {
                return;
            }

            Projectile laser = Instantiate(laserPrefab, laserMuzzle.position, laserMuzzle.rotation);
            laser.gameObject.SetActive(true);
            laser.team = team;
            laser.owner = gameObject;
            SpawnMuzzleFlash(laserMuzzle);
        }

        private void FireMissile()
        {
            if (missilePrefab == null || missileMuzzle == null)
            {
                return;
            }

            HomingMissile missile = Instantiate(missilePrefab, missileMuzzle.position, missileMuzzle.rotation);
            missile.gameObject.SetActive(true);
            missile.team = team;
            missile.owner = gameObject;
            missile.target = lockOnSystem != null ? lockOnSystem.CurrentTarget : null;
            SpawnMuzzleFlash(missileMuzzle);
        }

        private void SpawnMuzzleFlash(Transform muzzle)
        {
            GameObject flashObject = new GameObject("Aether Muzzle Flash");
            flashObject.transform.position = muzzle.position;

            Light flash = flashObject.AddComponent<Light>();
            flash.type = LightType.Point;
            flash.range = 7f;
            flash.intensity = flashIntensity;
            flash.color = muzzleFlashColor;

            Destroy(flashObject, flashLifetime);
        }
    }
}
